version: "3.8"

services:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - chedjou03-networks

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - chedjou03-networks
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - chedjou03-networks

  configserver:
    image: chedjou03/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - chedjou03-networks
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  eurekaserver:
    image: chedjou03/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8060:8060"
    networks:
      - chedjou03-networks
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  accounts:
    image: chedjou03/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - chedjou03-networks
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8060/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/


  loans:
    image: chedjou03/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - chedjou03-networks
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8060/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  cards:
    image: chedjou03/cards:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - chedjou03-networks
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8060/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gatewayserver:
    image: chedjou03/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8050:8050"
    networks:
      - chedjou03-networks
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - accounts
      - loans
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 5
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8060/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
   chedjou03-networks:
